// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiKJKsRJ8bDFRD5rbXlkiL5QR938wGpNc',
    appId: '1:432634748312:web:f67dafa57daf601e695fed',
    messagingSenderId: '432634748312',
    projectId: 'linkly-bad82',
    authDomain: 'linkly-bad82.firebaseapp.com',
    storageBucket: 'linkly-bad82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTOnLNcs62T6oGmGfnqOq026MG5XDOp9E',
    appId: '1:432634748312:android:5bb5ee424ed20a3a695fed',
    messagingSenderId: '432634748312',
    projectId: 'linkly-bad82',
    storageBucket: 'linkly-bad82.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiKJKsRJ8bDFRD5rbXlkiL5QR938wGpNc',
    appId: '1:432634748312:web:a6e287e4c407cdd7695fed',
    messagingSenderId: '432634748312',
    projectId: 'linkly-bad82',
    authDomain: 'linkly-bad82.firebaseapp.com',
    storageBucket: 'linkly-bad82.firebasestorage.app',
  );

}